// <auto-generated />
namespace Gallery.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Media_Name_Lenght_Changed_Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Media_Name_Lenght_Changed_Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051122169_Media_Name_Lenght_Changed_Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
