// <auto-generated />
namespace Gallery.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Added_IsDeleted_Property_To_Media : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_IsDeleted_Property_To_Media));
        
        string IMigrationMetadata.Id
        {
            get { return "202005251218405_Added_IsDeleted_Property_To_Media"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
